application: acdha-trendoid
version: 1
runtime: python
api_version: 1

builtins:
- appstats: on
- datastore_admin: on

handlers:
- url: /static/
  static_dir: static
  expiration: 30d
- url: /.*
  script: trendoid.py
