application: acdha-trendoid
version: 1
runtime: python
api_version: 1

builtins:
- appstats: on
- datastore_admin: on

handlers:
- url: /static/
  static_dir: static
  expiration: 30d
- url: /.*
  script: trendoid.py

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]$
- ^(.*/)?\..*
- ^static/external/dygraphs/(?!dygraph-combined.js).*$